[workspace]
members = ["plugins/*"]

[package]
name = "sora"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sora"
path = "bin/sora.rs"

[dependencies]
anyhow = "1.0"
libloading = "0.8"
thiserror = "1.0"
